### ISSUE TITLE
Week 8 ready for review

### ISSUE THREAD

**Issue by akcuster** [akcuster/Week8ConsumingCatFactsAPI#1]
@pawaitemadisoncollege I'm finished with week 8.

The key learnings were a better understanding of how to consume RESTful web services and practice with reading the documentation for different APIs. 

The main challenge I faced was implementing the web service I want to use for my indie project. The way the generated POJOs are set up made it difficult for me to figure out how to access the information that I need with the skills that I've learned so far. I just need to play around with it a bit more and do some googling, but in the meantime created a stand-alone project for the exercise. 

Once I decided to do the stand-alone project, I didn't really run into any problems.

**Comment by pawaitemadisoncollege** [comment]
I didn't know there was a cat-fact api @akcuster!!! How fun!

Just a couple things if/when you do implement an api in a "real" project:
- [ ] The base url and any relevant api keys are best placed in a property file: https://github.com/akcuster/Week8ConsumingCatFactsAPI/blob/0c933dbe5dda013b48b01fcef578aeb0e323df41/src/main/java/com/acuster/persistence/CatFactDao.java#L19
- [ ] This method would be more flexible b y accepting a fact number as a parameter: https://github.com/akcuster/Week8ConsumingCatFactsAPI/blob/0c933dbe5dda013b48b01fcef578aeb0e323df41/src/main/java/com/acuster/persistence/CatFactDao.java#L15


If you need help with that more complex api, let me know!
